### PR TITLE
Improve README indetation formatting of code snippets 

### PR DESCRIPTION
**Pull request by obumnwabude**
Use two spaces for code indentations everywhere. 
Did this to unify the formatting.

Initialize Memphis connection in OnModuleInit lifecycle method.
The OnModuleInit method is the best place for such asynchronous callback.
This is because it is a lifecycle method

Did this "OnModuleInit-Change" for only the first snippet. 
Supposedly, the developer might do other things with the "value-setting"
initializations of the other code snippets.

### CODE REVIEW

**Comment by idanasulinmemphis** [comment]
Hi @obumnwabude, thanks for the feedback, it seems like we can merge your changes, but please open this PR to branch named staging

**Comment by obumnwabude** [comment]
Hi @idanasulinmemphis, I switched the base branch to staging instead of recreating a new pull request. I think it should solve the issue.

**Comment by idanasulinmemphis** [comment]
There are a few changes made by us in the last week, so please notice the differences between the parameters passing to the connect function.
So please take a look and commit that and then I'll be able to approve your PR

**Comment by obumnwabude** [comment]
It's like those changes do not affect this pull request. Or rather, its like I have addressed the changes. You know this pull request only targeted the README file. And GitHub is not showing the resolve conflicts again as it is showing in the other PR.

**Comment by idanasulinmemphis** [comment]
I noticed it is only the readme file, but if you will take a closer look there is a section of the connect function (line 95).
We have made some changes there

**Comment by idanasulinmemphis** [comment]
As discussed on Discord, please open this PR to master branch

**Pull request closed without merging**
