### PR TITLE
feat: add .stop() function on consumers

### LINKED ISSUE #53: [Feature Request] Close a consumer listener function
We need to enable the ability to close a consumer listener in our node.js SDK.
When trying to consume messages by sending a GET request, the listener stays open.

```
const express = require('express');
const memphis = require("memphis-dev");
require('dotenv').config()
var bodyParser = require('body-parser');
var cors = require('cors');
const { default: nodeTest } = require('node:test');
const app = express();
const PORT = 3000;

app.use(cors());

app.use(express.static('public'));
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({
    extended: true
}));

let producer, consumer, myData = [];

(async function () {
    try {
        await memphis.connect({
            host: "broker.sandbox.memphis.dev",
            username: process.env.MEMPHIS_USERNAME,
            connectionToken: process.env.MEMPHIS_CT
        });
        producer = await memphis.producer({
            stationName: "glitch",
            producerName: "myProducer"
        });
        consumer = await memphis.consumer({
            stationName: "glitch",
            consumerName: "myConsumer",
            consumerGroup: ""
        });
        consumer.on("message", message => {
            myData.push(message.getData().toString());
            message.ack();
        });
    } catch (ex) {
        console.log(ex);
        memphis.close();
    }
})();

app.get('/', (req, res) => {
    res.send('Hello World!');
});

app.post('/produce', async function (req, res, next) {
    var msg = req.body.msg;
    await producer.produce({
        message: Buffer.from(msg)
    });
    res.sendStatus(200);
});

app.get('/consume', async function (req, res, next) {
    console.log("CONSUME");

    res.json(myData);
    myData = [];
});

app.listen(PORT, () => console.log(`Server listening on port: ${PORT}`));
```

### PR DESCRIPTION
**Pull request by obumnwabude**
privately store a reference to subscriptions in the Consumer class.
unsubscribe from these subscriptions in the .stop() function.
also clear pinging and pulling intervals in the .stop() function.
call this consumer.stop() function when the consumer is been removed from cachedConsumers.
also call this function in memphis.close().

this solution is mainly pulled out from this #130 PR by @Talg123 

closes #53

### CODE REVIEW

**Comment by idanasulinmemphis** [comment]
Hi @obumnwabude, a few conflicts have arisen since we've made some changes in the way we are consuming messages (because we now support partitions).
Please resolve them, and I'll review them again

**Comment by idanasulinmemphis** [comment]
Hi @obumnwabude looks ok.
2 things - remove the build files from the PR and add a relevant section on the readme

**Comment by obumnwabude** [comment]
@idanasulinmemphis 

I have added a section in the README. 

As for the build files, I don't think I can technically remove them because it will mean deleting them except I don't understand you well. Anyways, I have resolved the conflicts, please merge and rebuild to have it the feature in the final build.

**Review by idanasulinmemphis — APPROVED** [review]

**Comment by idanasulinmemphis** [comment]
@obumnwabude looks great now, approved and merged.
Thanks for another great contribution

**Comment by Talg123** [comment]
Great Job! :)

**Pull request merged**
